apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  # PV name
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
# the above all for volume claim
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: "ebs-static-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    # mount volume to perticular directory for safe data
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  # add persistent volume to pod
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "ebs-static-demo"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007